import Header from '@/components/Header';
import './globals.scss';
import Preheader from '@/components/Preheader';
import Footer from '@/components/Footer';
import { fetcher } from '@/helpers/utils';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const dataPreheader = await fetcher(
    'http://localhost:1337/api/annonces', {
      next: { revalidate: 3600 }
    }
  );
  
  return (
    <html lang="fr">
      <body>
        <Preheader data={dataPreheader?.data} />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
