import Header from '@/components/Header'
import './globals.scss'
import Preheader from '@/components/Preheader'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>
        <Preheader />
        <Header />
        {children}</body>
    </html>
  )
}
